CFLAGS=-Wall -Wextra -Werror
CLIBS=-lm
DEF=-D $(join $1,_IMPL) -D $(join $1,_MAIN)

all: main

test_rand: random.c stats.c
	$(CC) $(CFLAGS) $(CLIBS) $(call DEF, RAND) random.c
	./a.out

test_event_heap: event_heap.c event.c
	$(CC) $(CFLAGS) $(call DEF, EVENT_HEAP) event_heap.c
	./a.out

test_queue: event.c queue.c
	$(CC) $(CFLAGS) $(call DEF, QUEUE) queue.c
	./a.out

test_system: event_heap.c event.c queue.c random.c stats.c system.c
	$(CC) $(CFLAGS) $(call DEF, SYSTEM) system.c
	./a.out

main: main.c event_heap.c event.c queue.c random.c
	$(CC) $(CFLAGS) $(CLIBS) main.c -o main

clean:
	rm -f *.out